#! /bin/sh

isUpstart() {
    /sbin/init --version 2>/dev/null | grep -q 'upstart'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

isSystemd() {
    /bin/systemctl 2>/dev/null | grep -q '\-\.mount'
    #echo "result=$?"
    if [ "$?" = "0" ]; then
        return 0
    else 
        return 1
    fi
}

if ! getent group audiostream >/dev/null; then
    addgroup --system audiostream
fi

if ! getent passwd audiostream >/dev/null; then
    adduser --system --ingroup audiostream --home /var/lib/audiostream audiostream
fi

# add groups to user
addgroup audiostream pulse
addgroup audiostream pulse-access
addgroup audiostream audio

if [ -d /var/lib/playout/ ]; then
  chown audiostream:audiostream /var/lib/playout/
  chmod 0750 /var/lib/audiostream/
fi

if [ -d /var/run/playout/ ]; then
  chown audiostream:audiostream /var/run/playout/
  chmod 0775 /var/run/playout/
fi

if [ -d /var/log/playout/ ]; then
  chgrp audiostream /var/log/playout/
  chmod 0775 /var/log/playout/
fi

# set group
chgrp audiostream /etc/playout/liquidsoap/*.conf
chgrp audiostream /etc/init/playout-liquidsoap.conf
chgrp audiostream /etc/logrotate.d/playout-liquidsoap


if isUpstart; then
    initctl reload-configuration
	start playout-liquidsoap
fi

if isSystemd; then
	systemctl enable playout-liquidsoap
	systemctl start playout-liquidsoap
fi

#DEBHELPER#
exit 0
